version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - /home/ubuntu/.env.prod
    volumes:
      - /home/ubuntu/ssl:/ssl

  frontend:
    build: ./frontend
    ports:
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/ssl
