version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45

