version: '3.8'

services:
  web:
    build: ./backend
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - /home/ubuntu/.env.prod
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
