# Generated by Django 4.2.4 on 2023-09-22 18:58

from django.db import migrations
from django.contrib.auth.management import create_permissions

# Django faria isso depois das migrations, mas numa ordem diferente da que
# precisamos. Essa função cria as permissões para o grupo que será criado
# no passo posterior.
def migrate_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

class Migration(migrations.Migration):

    dependencies = [
            ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(migrate_permissions),
    ]
