# Generated by Django 4.2.7 on 2023-11-04 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Insira o nome do autor', max_length=255, verbose_name='Nome do autor*')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Insira o título do artigo', max_length=255, verbose_name='Título do artigo*')),
                ('ano_publicacao', models.CharField(help_text='Insira o ano de publicação do artigo', max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'Campo precisa ter 4 dígitos.')], verbose_name='Ano de publicação*')),
                ('link', models.URLField(blank=True, help_text='Insira o link para o artigo (Opcional)', verbose_name='Link')),
                ('autores', models.ManyToManyField(help_text='Para selecionar mais de um autor, segure a tecla Ctrl ao clicar.', to='artigos.autor', verbose_name='Autores*')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
