# Generated by Django 4.2.7 on 2023-11-04 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_insere_exemplos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='ano_publicacao',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4, 'Campo precisa ter 4 dígitos.')], verbose_name='Ano de publicação'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autores',
            field=models.ManyToManyField(to='artigos.autor', verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Título do artigo'),
        ),
    ]
