# Generated by Django 4.2.7 on 2023-11-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_alter_artigo_ano_publicacao_alter_artigo_autores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='autores',
            field=models.ManyToManyField(blank=True, to='artigos.autor', verbose_name='Autores'),
        ),
    ]
